

service: hsl-home-backend

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment:
    REGION: ${self:provider.region}

functions:
  getStopData:
    handler: handler.getStopData
    environment:
  